{% set name = "dbt-snowflake" %}
{% set version = "1.10.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: c0a99f4291f3abc66a85f382fa891c2cfc23e2999e2fcb0fe941d083d4e4cdea

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<310]

requirements:
  host:
    - python
    - pip
    - hatchling
  run:
    - python
    - dbt-common >=1.10,<2.0
    - dbt-adapters >=1.16.6,<2.0
    # lower bound pin due to platform_detection_timeout_seconds parameter
    - snowflake-connector-python >=3.17.2,<4.0.0
    - certifi <2025.4.26
    # add dbt-core to ensure backwards compatibility of installation, this is not a functional dependency
    - dbt-core >=1.10.0
    # installed via dbt-core but referenced directly; don't pin to avoid version conflicts with dbt-core
    - agate

# Tests not adapted for py313
# >   raise AttributeError(item)
# E   AttributeError: __class_getitem__
test:
  source_files:
    - tests
    - test.env.example
    - src/dbt/include/snowflake/macros
  imports:
    - dbt.adapters.snowflake
  commands:
    - pip check
    - cp test.env.example test.env  # [unix]
    - copy test.env.example test.env  # [win]
    - pytest -v tests/unit  # [py<313]
  requires:
    - pip
    - pytest

about:
  home: https://github.com/dbt-labs/dbt-snowflake
  summary: The Snowflake adapter plugin for dbt
  description: The dbt-snowflake package contains all of the code enabling dbt to work with Snowflake.
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  dev_url: https://github.com/dbt-labs/dbt-snowflake
  doc_url: https://docs.getdbt.com/docs/core/connect-data-platform/snowflake-setup

extra:
  recipe-maintainers:
    - maresb
    - thewchan
