{% set name = "dbt-snowflake" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dbt-snowflake-{{ version }}.tar.gz
  sha256: 0bcc2b214b8129c0e086a82a4d56fb80ad8e6edd9b8fef4b7c884cf403ad9f40

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    # Ref: <https://www.marcelotrevisani.com/grayskull>
    - cryptography >=3.2,<37.0.0
    - dbt-core >=1.2.0,<1.3  # Changed ==1.1.* to <1.2
    - python >=3.7
    - requests <3.0.0
    - snowflake-connector-python >=2.4.1,<2.8.0

test:
  imports:
    - dbt
    - dbt.adapters
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dbt-labs/dbt-snowflake
  summary: The Snowflake adapter plugin for dbt
  license: Apache-2.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - maresb
    - thewchan
