{% set name = "dbt-snowflake" %}
{% set version = "1.12.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: d384c2eb7ccb5dc91f9c1e89a8041b9121ab8605f580a2e90f806e6ef013d05e

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  # No certifi <2025.4.26 for Python 3.14+
  skip: true  # [py<310 or py>313]

requirements:
  host:
    - pip
    - python
    - hatchling
  run:
    - python
    - dbt-common >=1.10,<2.0
    - dbt-adapters >=1.24.4,<2.0
    # lower bound pin due to platform_detection_timeout_seconds parameter
    # snowflake-connector-python[secure-local-storage]>=4.2.0,<5.0.0
    - snowflake-connector-python >=4.2.0,<5.0.0
    # secure-local-storage -> keyring
    - keyring >=23.1.0,<26.0.0
    - certifi <2025.4.26
    # add dbt-core to ensure backwards compatibility of installation, this is not a functional dependency
    - dbt-core >=1.10.0,<2.0
    # installed via dbt-core but referenced directly; don't pin to avoid version conflicts with dbt-core
    - agate

test:
  source_files:
    - tests
    - test.env.example
    - src/dbt/include/snowflake/macros
  imports:
    - dbt.adapters.snowflake
  commands:
    - pip check
    - cp test.env.example test.env  # [unix]
    - copy test.env.example test.env  # [win]
    # Tests not adapted for py313
    # >   raise AttributeError(item)
    # E   AttributeError: __class_getitem__
    - pytest -v tests/unit  # [py<313]
  requires:
    - pip
    - pytest

about:
  home: https://github.com/dbt-labs/dbt-snowflake
  summary: The Snowflake adapter plugin for dbt
  description: The dbt-snowflake package contains all of the code enabling dbt to work with Snowflake.
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  dev_url: https://github.com/dbt-labs/dbt-snowflake
  doc_url: https://docs.getdbt.com/docs/core/connect-data-platform/snowflake-setup

extra:
  recipe-maintainers:
    - maresb
    - thewchan
